### ISSUE TITLE
Problem: site not built on Master

### ISSUE THREAD

**Issue by gazhayes** [fractalide/fractalide-website-styx#107]
Problem: the site is being built on the gh-pages branch.

Solution: it's completely possible for Github pages to run from a subdirectory on the Master branch, if only having one branch is important to the project. There are some instructions here on how to do it: https://gist.github.com/cobyism/4730490

**Comment by sjmackenzie** [comment]
interesting, I'll have a ponder on this. Probably easier for multiple parties to collaborate and test on different devices without having to set up their own local server.

**Comment by clacke** [comment]
I'll have a look at that link too. GitLab Pages was trivial to set up with an arbitrary site generator running on GitLab CI, so I imagine GitHub Pages and Travis should be able to do the same thing.

**Comment by clacke** [comment]
Hm, that link was about keeping generated files in a subtree and using `git subtree` to push.

https://github.com/X1011/git-directory-deploy/blob/master/readme.md seems more relevant.

But in the end, all it is about really is just writing to the `gh-pages` branch.

I hope (and expect) there is a way to store and use a github token on Travis without the public seeing it, so it can write to gh-pages from a travis job.

**Comment by clacke** [comment]
On GL it's as simple as a few lines, e.g. https://gitlab.com/risbrokyrkan/risbrokyrkan/blob/master/.gitlab-ci.yml .

They are no longer playing catch-up with GH, they're ahead.

**Comment by sjmackenzie** [comment]
Hydra will be setup soon. Hydra can write to `gh-pages`.

**Comment by gazhayes** [comment]
> They are no longer playing catch-up with GH, they're ahead.

GH's limitations are starting to annoy me on many levels, I'm probably going to end up rolling my own GL server and C4 the platform itself.

**Comment by sjmackenzie** [comment]
the gauntlets are off! 

Yeah hydra will deploy directly to the upcoming webserver so I don't think we need to commit generated files to the repo.

**Comment by sjmackenzie** [comment]
builds on master now
