### ISSUE TITLE
Problem: fractalide.com is not using https

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide-website-styx#120]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Solution: Use the information in the article above to activate https.

Care must be taken that any resources loaded -- media, javascript, etc -- are loaded either over https or protocol-relative, or we'd have issues with mixed-content warnings.

**Comment by clacke** [comment]
A quick look shows that there is almost nothing to be done except flipping a switch, as Pages will automatically use letsencrypt to get the cert.

**Comment by clacke** [comment]
I think might mean you need to update to the new A records first.

You mean with the new server, we will be hosting the pages ourselves?

**Comment by sjmackenzie** [comment]
Yeah pretty much. But as there is no logins on the site and it's static probably HTTPS for the moment isn't a high priority.

**Comment by sjmackenzie** [comment]
https://fractalide.com/
