### ISSUE TITLE
Problem: spacing between images on hyperflow pages is unequal

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide-website-styx#150]
**step to reproduce**
Navigate to http://fractalide.com/hyperflow/ using a desktop

**Actual behaviour**
<img width="1440" alt="screen shot 2018-05-22 at 10 24 38 am" src="https://user-images.githubusercontent.com/39090829/40338977-b4295f62-5daa-11e8-9ced-a218157f8ebe.png">

**Expected behaviour**
To have the same amount of space between the images

**Comment by miguelsimoni** [comment]
I used the gimp measure tool and it shows 16.1 and 16.6 pixels from one vertex to another...

**Comment by sjmackenzie** [comment]
yeah, it seems okay on @dapyh17d4 interfaces. It's still a bit wonky on mine. I'll take a screenshot for you.

**Comment by sjmackenzie** [comment]
![hyperflow-gap-difference](https://user-images.githubusercontent.com/158321/40577369-21893584-6137-11e8-8b1c-0c4213665d6a.png)
