### ISSUE TITLE
Problem: shared links to the site don't have a preview image

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide-website-styx#164]
Solution: make use of open graph and Twitter card tags in the page head. Probably best to make it just the logo (blue on black)

**Comment by miguelsimoni** [comment]
You can get a preview of the sharing link:

For Twitter:
https://cards-dev.twitter.com/validator

For Facebook:
https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Ffractalide.com%2F

**Comment by sjmackenzie** [comment]
https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Ffractalide.com%2F said:
```
Invalid URL Provided og:image URL, /img/logo.png was not a valid URL.
```
and https://cards-dev.twitter.com/validator said:
```
Log
INFO:  Page fetched successfully
INFO:  15 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully
```
This #166 is deployed

**Comment by miguelsimoni** [comment]
## From Facebook Sharing Debugger:

### Warnings That Should Be Fixed

- **Invalid URL**: Provided og:image URL, /img/logo-blue-min.png was not a valid URL.
- **Missing Properties**: The following required properties are missing: og:description, fb:app_id

**Comment by sjmackenzie** [comment]
Well, http://fractalide.com/img/logo-blue-min.png looks valid to me!

**Comment by sjmackenzie** [comment]
Ah maybe it's too long. If that's the case then just use the logo without the wording. (if one is available)

**Comment by miguelsimoni** [comment]
It's the URL, it must be the absolute path.

**Comment by sjmackenzie** [comment]
Ah yeah, well that makes sense :-)

**Comment by sjmackenzie** [comment]
I'm getting an error:

## From Facebook Sharing Debugger:

### Warnings That Should Be Fixed

- **Image Too Small**: Provided og:image URL, http://fractalide.com/img/roadmap-min/fractal-min.png was not valid because it did not meet the minimum size constraint of 200px by 200px.
- **Missing Properties**: The following required properties are missing: fb:app_id

@dapyh17d4 could we have a fractalide logo 200px by 200px (blue on black or whatever you think is appropriate) for the twitter and open graph sharing functionality please.

**Comment by dapyh17d4** [comment]
@sjmackenzie Since you mentioned that the minimum size requirement is 200px X 200px, I'd suggest uploading a larger image (400px X 400px) so that it looks crisp. Just in case that's not allowed, please use the 200px X 200px image.

400px X 400px
https://drive.google.com/open?id=1ksga_7bzWXDBqiZ6X468W84iV2FxsweW

200px X 200px 
https://drive.google.com/open?id=1Ci5PLy96DE_WbdxBmOFNiTbvMD1uBV4t

**Comment by sjmackenzie** [comment]
Thanks @dapyh17d4 yeah the error message says min 200px by 200px, I don't know what the max size is :-) get back to you shortly!

**Comment by sjmackenzie** [comment]
Okay it works well!
