### ISSUE TITLE
Implement stake pool pages and update the menu

### ISSUE THREAD

**Issue by dapyh17d4** [fractalide/fractalide-website-styx#192]
**Version history**
Version 1.0, Sep 26, 2018 Added designs of the desktop version
Version 1.1, Sep 28, 2018 Added designs of the mobile versions and added image assets
Version 1.2, Sep 29, 2018 Added "Email me when it's live" button to LUCEO page and ADA page, added "I want to run a LUCEO stakepool" button to LUCEO page
Version 1.3, Oct 1, 2018 Updated mobile designs for XTZ page

**What has been changed in the menu**
- Removed “Home” (Users can click the Fractalide logo to go to "Home")
- Moved “Blog", Twitter icon, and RSS  icon to "Resources" dropdown
- Added "Stake Pools" dropdown with 3 items: Cardano (LUCEO),  Cardano (ADA), Tezos (XTZ)
Clicking the name of the pages in the "Stake Pools" dropdown will take users to the respective pages.
![menu-05](https://user-images.githubusercontent.com/39090829/46220038-900d8900-c37b-11e8-96ce-8b6055f3b850.png)

**Image assets**
https://drive.google.com/open?id=1JDKNf8904ybS6YLWqAS7STt_oiUVXeTy

**Desktop**
Clicking "Copy" will copy the address to the clipboard.
![stake-pool-luceo-01](https://user-images.githubusercontent.com/39090829/46246257-55fcbf80-c42d-11e8-8354-d61f075c3278.png)
![stake-pool-ada-01](https://user-images.githubusercontent.com/39090829/46246258-59904680-c42d-11e8-8907-446e700caa56.png)
![stake-pool-xtz-01](https://user-images.githubusercontent.com/39090829/46246260-5b5a0a00-c42d-11e8-9322-052c4daa105d.png)

**Delegation address details**
There are 2 states:
- When it's not full, display the address. (Background: #FFFFFF, "Copy" color: #58B4CD)
- When it's full, display "We're full!" (1px border #58B4CD, text color: #0D3E4C)
![stake-pool-address-01](https://user-images.githubusercontent.com/39090829/46219725-a9620580-c37a-11e8-9770-e7a4dd19c61a.png)

**Tablet**
![stake-pool-luceo-tab-01](https://user-images.githubusercontent.com/39090829/46246266-6e6cda00-c42d-11e8-958c-fefdd4afb5c9.png)
![stake-pool-ada-tab-01](https://user-images.githubusercontent.com/39090829/46246268-72006100-c42d-11e8-89e3-176a8d0dc7e0.png)
![stake-pool-xtz-tab-01](https://user-images.githubusercontent.com/39090829/46301513-1ecb1180-c5d9-11e8-8c76-7ffb3c9fdf56.png)
![stake-pool-address-tab-01](https://user-images.githubusercontent.com/39090829/46219766-ca2a5b00-c37a-11e8-98f2-11397d5527c0.png)

**Phone**
![stake-pool-luceo-phone-01](https://user-images.githubusercontent.com/39090829/46246272-7fb5e680-c42d-11e8-8371-08f19ca8d885.png)
![stake-pool-ada-phone-01](https://user-images.githubusercontent.com/39090829/46246273-817faa00-c42d-11e8-9dc1-d1f819ce6117.png)
![stake-pool-xtz-phone-01](https://user-images.githubusercontent.com/39090829/46301504-14a91300-c5d9-11e8-8701-bd19a55511ae.png)
![stake-pool-address-phone-01](https://user-images.githubusercontent.com/39090829/46219807-df9f8500-c37a-11e8-8f36-ec650d5d886b.png)

**Note**
@sjmackenzie will provide the text and the links to the forms (where the buttons will go to)

**Comment by sjmackenzie** [comment]
Opening as the mobile pages might not be done yet.
