### ISSUE TITLE
Problem: no clear way to run the `hugo server -D`

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide-website-styx#26]
I tried running `hugo server -D` and it fails with this message:

```
$ hugo server -D
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (Config File "config" Not Found in "[/home/stewart/dev/fractalide/fractalide-website-styx/fractalide-hugo-theme]")
```

@miguelsimoni  please advise on how to run this hugo theme.

**Comment by miguelsimoni** [comment]
Since the [example site](https://github.com/fractalide/fractalide-website-styx/tree/master/fractalide-hugo-theme/exampleSite) has configured the path to fractalide-hugo-theme as "../..", you can run the hugo server from the exampleSite directory.

```
$ cd fractalide-website-styx/fractalide-hugo-theme/exampleSite
$ hugo server
```

(Instructions added to README.md)
