### ISSUE TITLE
Problem: roadmap on nix is different to hugo despite same css

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide-website-styx#61]
### Actual Nix Site
![nix-css](https://user-images.githubusercontent.com/158321/39080755-a1b3a33e-4567-11e8-9eab-64f2aea876a6.png)

The above is exactly the same CSS as the hugo theme, yet it displays incorrectly.

### Reference hugo site
![hugo-css](https://user-images.githubusercontent.com/158321/39080760-b1703d82-4567-11e8-8f79-65191cdd9ac4.png)

This is what the hugo site looks like.

Note please merge https://github.com/fractalide/fractalide-website-styx/pull/60 first. (I also removed the "Deployed" in this PR.

**Comment by sjmackenzie** [comment]
![nix-css-expanded](https://user-images.githubusercontent.com/158321/39080970-48c7eb3c-456b-11e8-90c7-576b3762b9df.png)

The text should also stretch out and be smaller

![hugo-css-expanded](https://user-images.githubusercontent.com/158321/39080973-4daeadc0-456b-11e8-9b88-4e9f58c4a9d6.png)

**Comment by miguelsimoni** [comment]
I don't see discrepancies neither on the CSS nor on the HTML code between the hugo theme (roadmap/single.html) and the new nix site (roadmap.md).

I'm not sure how to run a preview of the new nix site but maybe something in the output is applying a text-center style to the progress bar, objectives and work done sections.
