### ISSUE TITLE
Problem: new-site: lorem ipsum content/contact.md

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide-website-styx#85]
Solution: Write the proper text.

**Comment by clacke** [comment]
@sjm88

**Comment by clacke** [comment]
@sjmackenzie

**Comment by sjmackenzie** [comment]
Ah yes! I'll get on it to, just checked into the hotel.

**Comment by clacke** [comment]
Ok, today the menus work on my network (PRC) and apparently `contact` isn't referenced anywhere?
