### ISSUE TITLE
Problem: unverified e-mail address on /faqs

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide-website-styx#89]
I'm putting info@fractalide.com at the bottom. I don't know if that's correct.

Solution: Put the correct address there or close this issue.

**Comment by clacke** [comment]
@sjmackenzie If info@fractalide.com is correct, please close this issue.

**Comment by sjmackenzie** [comment]
It's correct, mail server should be coming through any day now. Waiting on @qknight

**Comment by qknight** [comment]
We need some dns adjustments. Do you want to share your providers credentials with us or do you want to set them yourself?

Mailserver is for fractalide.com, or what domain? 

El 3 de mayo de 2018 13:02:53 CEST, Stewart Mackenzie <notifications@github.com> escribió:
>It's correct, mail server should be coming through any day now. Waiting
>on @qknight
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/fractalide/fractalide-website-styx/issues/89#issuecomment-386259326

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjmackenzie** [comment]
I'll mail you @qknight
